### ISSUE TITLE
Loss of precision in Python

### ISSUE THREAD

**Issue by scemama** [TREX-CoE/trexio#116]
I wrote the nuclear repulsion in a TREXIO file. The nuclear repulsion computed by quantum package is
```
* Nuclear repulsion energy                           9.189533758614488    
```

I store it in a TREXIO file, and when I read it back in Python I get:
```
trexio.read_nucleus_repulsion(f)
9.189534187316895
 ```

The value given by Python is the same with both the text and the HDF5 back-ends.

When I inspect the text files produced by the text backend, I can see that the value of the nuclear repulsion is correct:
```
nucleus_repulsion   9.1895337586144876e+00                                                   
```

So I believe there is a conversion from float64 to float32 in the python interface after reading, but I could not figure out where it comes from...

It seems that I get the problem only for scalars. Arrays seem to be OK.

**Comment by q-posev** [comment]
@scemama You can try to replace the [following line](https://github.com/TREX-CoE/trexio/blob/master/src/pytrexio.i#L44) with the following `%apply double *OUTPUT { double* const num};` and re-install the Python API

**Comment by scemama** [comment]
Thanks! It works! :-)
