### ISSUE TITLE
add 'r','w','a' options to trexio_open function (front end)

### ISSUE THREAD

**Issue by q-posev** [TREX-CoE/trexio#13]

**Comment by scemama** [comment]
'r' and 'w' is done in PR #14.
I don't see the difference between 'w' and 'a'.

**Comment by q-posev** [comment]
'a' (append) would correspond to the case when a user wants to write in existing file, e.g. writing some missing blocks or overwriting existing ones. It protects from removing the existing file with data. Returns an error if the file does not exist and suggests to open with 'w' mode.
'w' would always create a new file to write in it. If the file exists, calling with this mode should return an error saying that file already exists and cannot be created, thus it has to be opened with 'a' mode.
What do you think?

**Comment by scemama** [comment]
OK. But we should also have a way to do 'a' or 'w'.
We can do
- 'a' : the file should exist
- 'w' : the file may or may not exist
- 'c' : the file should not exist (c: create)
- 'r' : the file should exist

Evgeny Posenitskiy writes:

> 'a' (append) would correspond to the case when a user wants to write in existing file, e.g. writing some missing blocks or overwriting existing ones. It protects from removing the existing file with data. Returns an error if the file does not exist and suggests to open with 'w' mode.
> 'w' would always create a new file to write in it. If the file exists, calling with this mode should return an error saying that file already exists and cannot be created, thus it has to be opened with 'a' mode.
> What do you think?


-- 
Anthony Scemama
IRSAMC / Laboratoire de Chimie et Physique Quantiques
UMR5626 CNRS/UPS
Toulouse
