### ISSUE TITLE
MacOS ARM64 runners 

### ISSUE THREAD

**Issue by q-posev** [TREX-CoE/trexio#132]
[M1 runners might be made available for public projects next year](https://github.com/actions/runner-images/issues/8439#issuecomment-1755601587)

We would need to migrate old x86_64 wheel builds to these new runners to release ARM-64 compatible wheels

**Comment by q-posev** [comment]
Looks like [it's out](https://github.com/actions/runner-images/blob/main/images/macos/macos-13-arm64-Readme.md) earlier than expected. Will try during holidays!

**Comment by q-posev** [comment]
Q1 2024: https://github.com/github/roadmap/issues/819

**Comment by kgantchev** [comment]
Hi, I'm the CEO and co-founder of FlyCI.  You can also try the [FlyCI](https://www.flyci.net/)'s M1 and M2 runners.

Easily replace your M1 runners: 
```diff
jobs:
 ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m1
   steps:
   - name: 👀 Checkout repo
     uses: actions/checkout@v4
```

Exclusive M2 runners: 
```diff
jobs:
  ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m2
    steps:
      - name: 👀 Checkout repo
        uses: actions/checkout@v4
 ```
 
They're up to 2x faster and up to 2x cheaper than GitHub's. We'll be very happy to have you on board.

**Comment by q-posev** [comment]
Hi @kgantchev,
Thanks for reaching out! We are a small open source project with no budget for the CI. Thus, commercial runners are not an option for us.

**Comment by kgantchev** [comment]
Thanks for the response @q-posev, we offer 500 mins of free usage per month for OSS projects. So this might be a great option for you.
