### ISSUE TITLE
Static and dynamic library compilation with cmake result in static library only

### ISSUE THREAD

**Issue by stefabat** [TREX-CoE/trexio#155]
When enabling both the static and dynamic library compilation with cmake, only the static library is installed.
Steps to reproduce:

1. `git clone https://github.com/TREX-CoE/trexio.git`
2. `cd trexio`
3. `./autogen.sh`
4. `mkdir build && cd build`
5. `cmake -DBUILD_STATIC_LIBS=ON -DCMAKE_INSTALL_PREFIX=/opt/trexio ..`
6. `make`
7. `sudo make install`

If I now look into `/opt/trexio` I find:
```
16:51:00 ⟩ ll /opt/trexio/*
include:
.rw-r--r-- 200k root 23 May 16:49 trexio.h
.rw-r--r-- 393k root 23 May 16:49 trexio_f.f90

lib:
.rw-r--r-- 2.1M root 23 May 16:49 libtrexio.a
```

I would expect also the shared libraries to be there, since the option was enabled in cmake.

**Comment by q-posev** [comment]
@stefabat yes, this is expected since usually the user would build and link against either static or dynamic lib. At least it seems to be a common practice with cmake. Do you have a use case in mind when you need both libraries compiled?

If you check the src/CMakeLists.txt, you will see that the BUILD_SHARED_LIBS option is swapped to FALSE if BUILD_STATIC_LIBS is provided to cmake.

**Comment by stefabat** [comment]
I see. I actually do not know the common practice, hence I trust your judgement. I do not have a specific use-case, I was just expecting both to be compiled according to the options set in cmake (directly from a fresh build).
I am testing the various options to find the best way to have trexio automatically pulled, compiled and linked during CP2K's compilation and installation process.
Anyway, if you say it's normal, no problem at all. It's good to know.

**Comment by q-posev** [comment]
By default we compile a shared library and then if `BUILD_STATIC_LIBS` is set to `ON` - we compile a static one with CMake. It would be possible to compile both but this would require extra care with the build system on the user side (especially with CMake which may require separate treatment of dynamic and share libs).

So it depends how CP2K build system handles external dependencies (like BLAS for example), are they linked statically or dynamically? Static linking increases the size of the final binary files but may simplify dependency management. So far most users opted for dynamic linking.

**Comment by stefabat** [comment]
At this stage, I can decide whether they are linked statically or dynamically. Considering that the release cycles of trexio are relatively fast, perhaps dynamic linking is the best way to go.

**Comment by scemama** [comment]
If you compile an isolated version of TREXIO with your code from a tar.gz distribution, I suggest that you use static linking. You are sure that the library you use is the one you have compiled, whatever happens on your system. It gives you more control. In this way, you know exactly which version of TREXIO your users are linking with your code, and it helps debugging when you get emails from users.

If you consider TREXIO as an external dependency installed by the user or the system administrator (like you would do for zlib or mkl for example), then dynamic linking is a better choice.

**Comment by q-posev** [comment]
OK, I see. @stefabat @scemama feel fre to close the issue when you feel like it. I removed the `bug` label because it was not a bug but a misunderstanding on the CMake build.

**Comment by stefabat** [comment]
Alright, sounds good. I will see what works best for CP2K. Thanks for the help.
