### ISSUE TITLE
Partial ECPs

### ISSUE THREAD

**Issue by stefabat** [TREX-CoE/trexio#159]
I am not sure how to handle the case in which I have ECPs only for certain atoms in my system. For example, I am testing with the water molecule, and I have an ECP for the 1s of oxygen, but a normal basis set for H. So I need to populate the ECP group, however, there are certain entries that may be ambiguous, for example `max_ang_mom_plus_1`? Or in the end, because in `nucleus_index` there will be no entry pointing to the hydrogen indices, everything works out?

PS: I am collecting a list of comments/possible feature additions while implementing this interface that I will share when I finish. One of the feature addition could be the support for fully non-local pseudopotentials, such as the ones used in CP2K (separable dual space norm-conserving GTH pseudopotentials).

**Comment by q-posev** [comment]
By the `code` I mean the user code, which reads TREXIO format and converts into code-specific representation

**Comment by stefabat** [comment]
Alright, indeed that is what I have done. I initialize `max_ang_mom_plus_1` to all zeros, and only the relevant atoms will have something greater than zero.
