### ISSUE TITLE
decouple read/write from the corresponding group

### ISSUE THREAD

**Issue by q-posev** [TREX-CoE/trexio#16]
In the current implementation, when reading/writing a dataset, its dimensions are obtained by scanning the file for the corresponding attribute (e.g. `nucleus_num`). This is ok for groups like `nucleus` where dimensions of all datasets depend on `nucleus_num`.
However, this will not work for groups like `ecp`, `mo` etc., where some datasets depend on _num variables determined outside of the current group.

**Comment by scemama** [comment]
Exactly!

That's the reason why I pass the dimensioning variables from the front-end to the back end as arguments in the TEXT back end.

Take for example the rdm_one_e which is dimensioned by mo.num: The front end knows that, so it fetches mo.num, and then it passes it as an argument to the back-end function.
