### ISSUE TITLE
Python TREXIO HDF5

### ISSUE THREAD

**Issue by scemama** [TREX-CoE/trexio#163]
For users where HDF5 is not accessible with `pkg-config`, the Python TREXIO build disables HDF5, even if HDF5 can be used with `-lhdf5`. This is the case in CALMIP for example where HDF5 is activated with `module load`.
A few improvements can be made:
- [ ] Add a warning (in red!) when TREXIO is built without HDF5 support
- [ ] Better detection of HDF5
- [ ] Maybe two different pip packages: one with and one without HDF5.

**Comment by q-posev** [comment]
In [Python README](https://github.com/TREX-CoE/trexio/tree/master/python#installation-from-source) I explain how to provide a path to HDF5 via env variables prior to building the Python API in cases where HDF5 is not detected via `pkg-config`. 
I would say that it is a problem of CALMIP that `module load` does not update the `PKG_CONFIG_PATH` env variable..
I am strongly against the idea of two different pip packages. Our packaging is already complicated enough.

**Comment by q-posev** [comment]
In fact, I suspect that you have built the C API without HDF5. In the past, if `configure` was able to detect HDF5 and build the C library - `make python-install` would have get the right variables pre-set (look at `HDF5_CFLAGS` in `Makefile.am`).
So I suspect something went wrong during your `config` too.

**Comment by scemama** [comment]
OK. So I think we should put a warning in red when we compile the python module without HDF5 during the pip install, because it is hard to guess when the python scripts using trexio don't run properly.

**Comment by q-posev** [comment]
Yes, you can modify the https://github.com/TREX-CoE/trexio/blob/master/tools/prepare_python.sh script accordingly. There is already a warning printed for your case but it's not in red 🙂
