### ISSUE TITLE
Add function to convert error codes to strings.

### ISSUE THREAD

**Issue by scemama** [TREX-CoE/trexio#18]
Also, add TREX_ERRNO, and the decoding message will be obtained from errno.

**Comment by scemama** [comment]
I am doing similar things in QMCkl now. We will just copy/paste...

**Comment by q-posev** [comment]
Commit 4e47e497d50a6a4d2c75afc791e708cd30791c70 closes #18

**Comment by q-posev** [comment]
Commit 4e47e497d50a6a4d2c75afc791e708cd30791c70 closes #18
