### ISSUE TITLE
Locking: Multiple readers, single writer

### ISSUE THREAD

**Issue by scemama** [TREX-CoE/trexio#19]
Find how to do that in a reliable and efficient way...

**Comment by q-posev** [comment]
for hdf5: https://portal.hdfgroup.org/display/HDF5/Single+Writer+Multiple+Reader++-+SWMR

**Comment by scemama** [comment]
Good news!

3 mars 2021 19:00:18 Evgeny Posenitskiy <notifications@github.com>:

**Comment by q-posev** [comment]
For now I think the best solution for hdf5 is to introduce a new open mode (probably 's') that will act as 'w' but using the SWMR functionality which doesn't lock the file, thus allowing multiple readers to access it.

**Comment by scemama** [comment]
It is not yet clear to me if the SWMR mode should be the default or not. I have to think about it. Can we postpone a bit?
