### ISSUE TITLE
File locking in HDF5 back end

### ISSUE THREAD

**Issue by scemama** [TREX-CoE/trexio#4]

**Comment by scemama** [comment]
Done in #14 for TEXT back-end. To do with HDF5.

**Comment by q-posev** [comment]
File locking is activated by default starting from hdf5 v.1.10. This is why normally concurrent read should fail.
File locking can desactivated using the `export HDF5_USE_FILE_LOCKING=FALSE` command (more details [here](https://portal.hdfgroup.org/display/knowledge/How+to+disable+file+locking+-+flock) 
For an advanced single-write/multiple-readers scenario see issue #19
