### ISSUE TITLE
Thread locking

### ISSUE THREAD

**Issue by scemama** [TREX-CoE/trexio#5]
This should be done in the front end.

We need to be careful because the front end calls its own functions. So we should acquire the lock just before calling the back-end function in the switch statement.

**Comment by q-posev** [comment]
Thread locking is now done in the front end based on `pthread.h` (see `pthread_mutex_init/destroy`)
TODO: Check that it works properly for HDF5 back end and implement `trexio_hdf5_lock/unlock` if it does not
