### ISSUE TITLE
Version number in file

### ISSUE THREAD

**Issue by scemama** [TREX-CoE/trexio#53]
We should store in the file the version of the library that produced the file.
It is already stored in `include/config.h` as 

```
/* major version */                                                                          
#define TREXIO_VERSION_MAJOR 0

/* minor version */
#define TREXIO_VERSION_MINOR 2

/* patch version */
#define TREXIO_VERSION_PATCH 0

/* Version number of package */
#define VERSION "0.2.0"
```

**Comment by q-posev** [comment]
Good idea. But what if the user(s) used different versions to write different blocks of data in the same file (i.e. on 2 different machines and/or using 2 different codes)?
