### ISSUE TITLE
user name and machine in file?

### ISSUE THREAD

**Issue by scemama** [TREX-CoE/trexio#54]
It could be convenient to store the user name and name of the machine of the user who produced the file. We can easily get this info from the environment variables and write it when we close the file.
The question is : is it too much intrusive? 

It is also possible to have an environment variable (or a configuration file stored in the home directory of the user) which activates this feature.

**Comment by q-posev** [comment]
I have the same question here as for #53 (multiple users/different machines). The user name can also be specified manually in the `author` section of the `metadata` group.
